### ISSUE TITLE
Advatage of PSM-net

### ISSUE THREAD

**Issue by mohanish3795** [lucgiffon/psm-nets#1]
Hello, 

Sorry for earlier issue, I guess something went wrong. 

I have read your paper and I really kudos to the work :) 

I would like to know what is the advantage of using PSM net ? I tried the example provided and the number of non-zeros params are decreased but the size is larger. 
So, my question is does it provide some computation boost or something ? 

PS. can you please provide example for tucker and SVD decomposition to compare this approach ?

**Comment by lucgiffon** [comment]
I guess the issue is solved? If there was an error somewhere, or a mis-understanding, I'd be happy to fix it :)

**Comment by lucgiffon** [comment]
The current implementation does not benefit from sparsity because it doesn't use sparse and efficient layers matrix operations. Instead, each layer is basically the hadamard product of a "mask" matrix (full of zeros and ones) with the weight matrix (full of zeros and weights). The zeros need to be stored just like any other float. This is why the final model is larger in term of number of floats stored.

This implementation is just a proof of concept: it shows that it is possible to learn PSM nets. However, it is not usable as is if you actually need to speed up an architecture. If you want to use PSM nets to speed up or lighten an architecture, you need first to find a way to implement sparse matrix products efficiently. To my knowledge, such thing doesn't exist on the shelf yet.
